services:
  - type: web
    name: telegram-kotik-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: API_TOKEN
        value: 7812132389:AAHsNiYnCXDnmDYAD9MOpuIXg0FaGWLGzSU
